gphoto/libgphoto2

- po/de.po
Update German translation
- Convert PO file to UTF-8 encoding
- Update PO header
> Christian Kirbach <christian.kirbach@gmail.com>

- INSTALL
- camlibs/ptp2/library.c
Added USB ID for Canon EOS SL2 / Kiss X8 / 200D
Added USB ID for Ricoh Theta S and SC models
Added Git to install/build instructions
> Added USB IDs: Canon SL2, Ricoh Theta S/SC

- camlibs/ptp2/library.c
Hi, just a very simple patch to add the EOS M100. Capture/preview/config seems to be working fine.
> Add Canon EOS M100

- README.md
Having such list of bindings should help with discoverability.
> Add Bindings section to README

- camlibs/ptp2/library.c
So the topic is pretty much it.
> Add VID:PID for Canon EOS 4000D using the same config as 1000D

- INSTALL
Renamed pkgconfig -> pkg-config, this is the debian package.
> Rename dep package

- camlibs/ptp2/cameras/sony-a6300.txt
Update the f-number configuration of the Sony Alpha 6300
> Update config Sony Alpha 6300

- camlibs/ptp2/cameras/sony-dsc-rx0.txt
- camlibs/ptp2/library.c
As mentioned in #336 
Add USB ids and output data for Sony DSC-RX0 camera.
> add sony dsc-rx0

- camlibs/ptp2/config.c
> ptp2: Add cRAW image format for Canon EOS

- camlibs/ptp2/cameras/fuji-gfx-50r.txt
- camlibs/ptp2/library.c
Add Fujifilm GFX 50R usb ids to models and property summary txt
file
> Add Fujifilm GFX 50R

- camlibs/ptp2/library.c
> Add alias for Rebel EOS T6

- camlibs/ptp2/library.c
Until now, in case of manual focus, the d213 property will not change so we were
waiting for the 1 sec timeout. So I propose to check the current focus mode before
to skip the useless wait.
On the Sony DSC-RX0, when the focus is ready, the d213 property becomes
3 and not 2 so the timeout where always reached as you can see in the attached logs file.
So I check that the value of `0x213` is either 2 or 3.
[trigger_capture_logs.txt](https://github.com/gphoto/libgphoto2/files/3173420/trigger_capture_logs.txt)
> Reduce Sony PTP capture time in manual focus and on RX0 in automatic focus

- INSTALL
- camlibs/canon/doc/Protocol.xml
- camlibs/canon/usb.c
- camlibs/dimera/dimera3500.c
- camlibs/jd11/jd11.html
- camlibs/jl2005c/README.jl2005c
- camlibs/ptp2/chdk_live_view.h
- camlibs/ptp2/config.c
- camlibs/sierra/sierra.c
- camlibs/sonydscf55/sony.c
- camlibs/st2205/st2205.c
- camlibs/template/Makefile-files
- configure.ac
- tests/ddb/check-ddb.sh.in
Thanks in advance for reviewing.
> Fix minor typos

- camlibs/ptp2/config.c
In the case the requested value is not available on the camera, we got strange behavior before. Shutterspeed got to the end of the range and the other properties jumped 100 steps always around the requested value. 
Now, it is stopped when we go behind the requested value. So as a result the reached value is right the next behind the requested value. 
I think that is the best compromise.
Test: For F-Number: goto 2.0 than try to change to 2.7. Before it will jump 100 times between 2.5 and 2.8. Now it will simply go to 2.8 and stop. 
Shutterspeed similar.
> Fix when exact requested value is not possible

- camlibs/ptp2/ptp.h
> php2: Fix a typo in comment

- camlibs/ptp2/cameras/nikon-z5.txt
- camlibs/ptp2/library.c
Added Nikon Z5 USB is and camera summary nikon-z5.txt
> Added Nikon Z5

- camlibs/ptp2/config.c
Overshoot logic was always comparing values to determine if the desired target has been overshot. However, in case of enums this didn't work correctly, since enum values are not guaranteed to be in the sorted order.
For example, "Auto ISO Multi Frame Noise Reduction" has a higher numerical value than, say, "ISO 400 Multi Frame Noise Reduction" but comes earlier in the enum list, so trying to go from "ISO 102400" to "ISO 400 Mutli Frame Noise Reduction" would stop at "Auto ISO Multi Frame Noise Reduction" thinking that the value has been overshot and can't go any further.
This PR fixes the logic to use enum index for overshot comparisons instead when `useenumorder` is enabled.
~~Additionally, the overshot check is skipped on the first loop where we make a large leap, since overshooting is …
> Fix overshoot logic for Sony enums

- camlibs/lumix/lumix.c
- camlibs/st2205/Makefile-files
- configure.ac
- libgphoto2/gphoto2-setting.c
Signed-off-by: Jaroslav Škarvada <jskarvad@redhat.com>
> Fixed build in mingw

- camlibs/lumix/Makefile-files
This is to complement https://github.com/gphoto/libgphoto2/commit/5c8c0538714b170ad83b2095dcf42838d663a3d3
> Fix lumix linking on mingw

- camlibs/ptp2/config.c
- camlibs/ptp2/ptp.c
- camlibs/ptp2/ptp.h
This PR adds support for Panasonic BGH1 camera over PTP.
> Added PTP support for Panasonic BGH1

- camlibs/ptp2/config.c
Fixes #784 
https://user-images.githubusercontent.com/5686338/162192469-50d0b1c8-071f-4978-b2c2-2850e795036f.mp4
> Configure Canon cameras on shutdown

- libgphoto2_port/vusb/vcamera.c
`read` can (and, in my case, did) return partial result instead of reading the whole number of bytes provided, leading to errors.
I replaced `open` / `read` with `fopen` / `fread` instead, which don't suffer from this issue, as well as extracted into a helper function.
> Unify & fix file reading in vcamera

- libgphoto2_port/vusb/vcamera.c
- libgphoto2_port/vusb/vusb.c
Like https://github.com/gphoto/libgphoto2/commit/ac4546e0dddf580c7e7558531818423dd3c81c3f and https://github.com/gphoto/libgphoto2/pull/615, but for virtual camera too.
> Fix building virtual camera on macOS

- camlibs/ax203/ax203.c
- camlibs/docupen/docupen.c
- camlibs/ptp2/config.c
ptp2/config: remove a semicolon.
docupen: remove a semicolon.
ax203: remove a semicolon.
> Optimize some code statements

- camlibs/ptp2/library.c
- camlibs/ptp2/ptp.c
- camlibs/ptp2/ptp.h
https://github.com/gphoto/libgphoto2/issues/846
> Fix pointer issues in local PTP event queue in Nikon capture

- .github/workflows/ccpp.yml
This tries to add a CI build for OSX
Closes https://github.com/gphoto/libgphoto2/issues/857
> Add CI build for OSX

- .github/workflows/ccpp.yml
This PR is to help testing the CI builds.
For comments and reviews, go to https://github.com/gphoto/libgphoto2/pull/863
> Prepare gh action for OSX and Windows CI builds

- .cirrus.yml
https://github.com/gphoto/libgphoto2/issues/859
> Add CI build for FreeBSD via Cirrus CI

- libgphoto2_port/libgphoto2_port/gphoto2-port-log.c
This speeds up large file downloads considerably, as the data log string generation is skipped.
> Only format data log string when a data logger func is registered

- camlibs/ptp2/ptp.h
> unbreak support for ILCE-7C

- camlibs/ptp2/cameras/olympus-om-1-mark-ii.txt
- camlibs/ptp2/library.c
Add OM-1 Mark II support and debug file.
> Add OM System OM-1 Mark II support

- camlibs/ptp2/ptp-pack.c
- camlibs/ptp2/ptp.c
Details, see the 2 commit logs.
> Ptp cleanup

- camlibs/canon/canon.c
- camlibs/canon/library.c
- camlibs/gsmart300/gsmart300.c
- camlibs/ptp2/config.c
- camlibs/ptp2/library.c
- camlibs/ptp2/ptp-pack.c
- camlibs/spca50x/spca50x-sdram.c
- libgphoto2_port/gphoto2/gphoto2-port-log.h
Please "rebase and merge" this PR instead of "squash and merge" to keep the changes separate in the commit history as
they are really unrelated. I simply did not want to open a separate PR for each of them.
> Random fixes

- examples/ambs-lgp2-frontend/meson.build
- libgphoto2/gphoto2-endian.h.in
- libgphoto2/meson.build
- libgphoto2_port/libgphoto2_port/meson.build
- libgphoto2_port/meson.build
- libgphoto2_port/usbdiskdirect/meson.build
- libgphoto2_port/vusb/meson.build
- meson.build
Notably the missing gphoto2-endian.h generation was missing
> Incorporate some fixes to the meson build definition

- libgphoto2_port/libusb1/meson.build
- libgphoto2_port/meson.build
libusb detection was flawed, default to libusb1 like the autotools
ltdl need the header, we must check for it.
> Some meson fixes

- camlibs/pentax/pslr_scsi.h
- camlibs/ptp2/config.c
They all appear when building with meson among a ton of others.
> Some warning fixes

- meson.build
Fixes bfce85402137b79d6a75b13113604fde00794f02
> meson: align the minor rev with autotools

- .github/workflows/ccpp.yml
- .github/workflows/codeql-analysis.yml
- camlibs/casio/casio-qv.c
- camlibs/kodak/dc120/dc120.c
- camlibs/kodak/dc3200/library.c
- camlibs/pccam300/library.c
- camlibs/pccam600/library.c
- libgphoto2/gphoto2-endian.h.in
- libgphoto2/meson.build
- libgphoto2_port/libgphoto2_port/meson.build
- libgphoto2_port/tests/meson.build
- tests/meson.build
Contains also several commits to fix meson build system with macos and linux. Do not squash the commits.
> ci: Use Meson build system instead of autotools

- camlibs/ptp2/library.c
Fixes #969 for me, but I'm not sure if this is the correct fix.
> respond to CaptureComplete events from om-1 mkii cameras
