camlibs/ptp2/cameras/nikon-s2.txt, camlibs/ptp2/library.c
I'm not sure if I'm including all the details you're after, but this is what I did:
- Identified the usb id of the camera with `lsusb`
- Added the id to `ptp2/library.c` with the same capabilities as the previous model (S1)
- Compiled
- Ran `--summary` and `--list-all-config` and added the results as cameras/nikon-s2.txt
- Removed the serial number of the camera
Scream and shout if you need me to add anything else.
=> Add Nikon 1 S2

camlibs/ptp2/cameras/nikon-s2.txt
=> Add missing opcodes for Nikon 1 S2

libgphoto2-uninstalled.pc.in, libgphoto2.pc.in
The dependency on libexif need not be exposed to consumers of this
library.  This is fixed by moving libexif from Requires to
Requires.private in the pkg-config files.
=> Avoid overlinking of libexif

camlibs/ptp2/library.c, camlibs/ptp2/ptp.h
Here is a pull request for the proposed change. Let me know if i can fix something to bring the code up to your standards, and if this is a useful way to provide patches.
=> use SetObjectAttributes to remove new flag on cameras that support it

camlibs/ax203/jpeg_memsrcdest.c, camlibs/ax203/jpeg_memsrcdest.h, camlibs/jl2005c/jpeg_memsrcdest.c, camlibs/jl2005c/jpeg_memsrcdest.h
libjpeg.h in OpenEmbedded master (from libjpeg-turbo 1.5.0) provides
these methods if "JPEG_LIB_VERSION >= 80 ||
defined(MEM_SRCDST_SUPPORTED)".
The support for the jpeg_mem functions was added even when not
emulating the libjpeg8 API, controlled via the MEM_SRCDST_SUPPORTED
define, so checking for the version alone is not enough anymore.
See https://github.com/libjpeg-turbo/libjpeg-turbo/commit/ab70623eb29e09e67222be5b9e1ea320fe5aa0e9
This fixes errors about conflicting declarations (signed vs. unsigned
char).
Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>
=> jpeg_memsrcdest: extend feature check

camlibs/ptp2/library.c
Added commands for Nikon COOLPIX A which the camera doesn't list, but I've confirmed it does in fact support.  Allows for use of this camera, otherwise this camera doesn't work.
=> Adding capabilities for Nikon COOLPIX A

camlibs/ptp2/library.c, camlibs/ptp2/ptp-pack.c, camlibs/ptp2/ptp.h
Fix for Canon 80D: when adding objects, Canon 80D uses different event-code
Fix for Canon 750D: during live view, Canon 750D uses different blob code for JPG data
=> Fixes for Canon 80D and 750D

camlibs/ptp2/library.c, camlibs/ptp2/ptp.h
Rather than waiting for the new object event (which often is simply not emitted by the camera), the previously undocumented property 0xD215 is used.  When no image is in the camera's RAM, 0xD215 has a u16 value of 0x0. However, when an image is in RAM for download, the u16 value is 0x8001.  If two images are available, it's 0x8002, etc.  After the images are retrieved (downloaded), the 0xD215 property returns to 0x0.
The sony_capture method has been updated to use this new method instead of the unreliable new object event.  The timing for the capture commands has also been modified to reflect how the Sony RemoteCameraControl app initiates it.  This should also fix issue #87 .
Some background on the fix is provided here: https://www.kickstarter.com/projects/elijahparker/view-intervalometer- …
=> Fixed sony capture reliability issues. Tested with Sony A7SII

camlibs/ax203/ax203.c, camlibs/ax203/ax203.h
ax206_compress_jpeg() is only defined in camlibs/ax203/ax203_compress_jpeg.c when "defined(HAVE_LIBGD) && defined(HAVE_LIBJPEG)".
But always, camlibs/ax203/ax203.h declares it and camlibs/ax203/ax203.c uses it.
=> ax203: ax206_compress_jpeg can use only "defined(HAVE_LIBGD) && defined(HAVE_LIBJPEG)"

packaging/generic/print-camera-list.c
```c
print-camera-list.c: In function 'ddb_delayed_head':
print-camera-list.c:887:2: error: too many arguments to function 'gpi_enum_to_string'
gpi_enum_to_string(a->device_type,
^~~~~~~~~~~~~~~~~~
In file included from ../../libgphoto2_port/gphoto2/gphoto2-port-info-list.h:63:0,
from ../../gphoto2/gphoto2-abilities-list.h:30,
from ../../gphoto2/gphoto2-camera.h:50,
from print-camera-list.c:53:
../../libgphoto2_port/gphoto2/gphoto2-port-log.h:185:3: note: declared here
gpi_enum_to_string(const unsigned int _enum,
^~~~~~~~~~~~~~~~~~
print-camera-list.c:897:2: error: too many arguments to function 'gpi_enum_to_string'
gpi_enum_to_string(a->status,
^~~~~~~~~~~~~~~~~~
In file included from ../../libgphoto2_port/gphoto2/gphoto2-port-info-list.h:63:0,
from …
```
=> print-camera-list: fix gip_enum_to_string() usage

camlibs/ptp2/library.c
A set of 4 patches implementing some code cleanup/cosmetic related to the `camera_summary()` function in ptp2/library.c. It is mainly about reducing code duplication and noise (removing 100+ lines of code), improving maintainability. Tested with a EOS 5Dm4 -> outputs the exact same (English) text as before.
=> Cleanup of camera_summary()

camlibs/canon/canon.c
Relax datalen check so it accepts the minimum reqired for referenced data
(15th element).  Canon S45 returns 16 bytes for this query, and failed
the previous requirement for 28 bytes returned.
--
I have tested this change and it allows reading and control of zoom on my Canon S45
=> camlibs: canon_int_get_zoom - work with shorter response from S45

camlibs/ptp2/library.c, camlibs/ptp2/ptp.c, camlibs/ptp2/ptp.h
I've found out that liveview is indeed possible with many newer Sony Alpha cameras.  It simply requires fetching an object (jpeg) from 0xffffc002 (for comparison, captured images are fetched from 0xffffc001).
A challenge I ran into when implementing this was that objectinfo does not return anything useful for 0xffffc002, so I created a copy of ptp_getobject to include the size of the object fetched so that it can be handled correctly (ptp_getobject_with_size).  This seems to work well, however, feel free to take a different approach if something else will better fit the existing APIs.
Also, I have commented out the code in sony_capture for checking for the focus event -- in my testing, any use of events with the newest generation of Sony Alpha cameras causes it to occasionally hang (e.g., …
=> Sony liveview support, sony capture reliability

camlibs/ptp2/config.c
The values -4.5, -3.5, 3.5 and 4.5 were previously unsupported and showed
up as Unknown value xxxx.
=> Added -4.5, -3.5, 3.5 and 4.5 as values for exposurecompensation of EOS

packaging/generic/check-ptp-camera, packaging/linux-hotplug/gphoto-set-procperm, packaging/linux-hotplug/usbcam.console, packaging/linux-hotplug/usbcam.group, packaging/linux-hotplug/usbcam.user, packaging/linux-hotplug/usbcam.x11-app
Convert bash scripts to more generic shell scripts. This removes the strict bash dependency and the scripts should now run with any posix shell. Also fix the issues reported by shellcheck while at it.
This wasn't tested too much because I didn't quite know how to trigger the various hotplug events. Any help on that front is appreciated.
=> scripts: remove bashisms.

camlibs/ptp2/library.c, camlibs/ptp2/usb.c
Hi,
I just wanted to share some modifications I've done in the timeout management in PTP wait_for_event function : 
7c95ede - to avoid error printed when the gp_port_check_int() return a timeout during check_fast. I suppose it isn't an error since the check_fast purpose is a non-blocking check on interrupt endpoint.
ae93b58 - I checked the timeout value if the function fallback in "sonyout" (others than Canon and Nikon ?) as it is done for Canon and Nikon cameras.
Do not hesitate to comment.
Cheers,
=> Change PTP waif_for_event() timeout management for standard cameras

libgphoto2_port/libgphoto2_port/gphoto2-port-log.c
The gp_log_remove_func implementation had 2 severe issues:
* it moved way to few bytes
* it moved the wrong bytes to the wrong place, destroying libc memory
management structures (resulting in different types of crashes).
When the first item has to be removed, it moved a couple bytes from the
start of the array to the left (before the start of the array), instead
of moving the second and following items over the first one.
DISCLAMER: I had to quickly workaround the issues by disabling my gp_log_remove_func usage. This one-liner is untested. Please double check.
=> fix memory corruption in gp_log_remove_func

camlibs/ptp2/library.c, camlibs/ptp2/ptp-private.h, camlibs/ptp2/ptp.c, camlibs/ptp2/ptp.h, camlibs/ptp2/usb.c, libgphoto2_port/libusb1/libusb1.c
My goal with this PR is to improve the error reporting when using ptp2 (usb).
A patch to gphotofs will follow that take usage of this improvement.
There are 3 points of this PR:
- raise usb errors that are currently masked with a generic "PTP_ERROR_IO".
- add a new PTP_ERROR_NODEVICE to be able to pass through the missing device error detected by libusb.
- reworked event manager async queue for multiple purpose. (Main one being to not hide errors)
Please see the description message of each commit for more details.
=> Improve error reporting when using the ptp2 lib 

camlibs/ptp2/config.c, camlibs/ptp2/ptp-pack.c
On my Canon 1300D, I was unable to adjust the white balance to negative values (both `whitebalanceadjusta` and `whitebalanceadjustb`). This is problematic, since it would limit the possible WB settings to a quarter of the possibilities. The horizontal Blue-Amber axis is controlled by `whitebalanceadjusta` (positive values are amber), the vertical Green-Magenta axis is controlled by `whitebalanceadjustb` (positive values are green).
When trying to set negative values, I got a "Device is busy" error (code -110). Getting the value worked fine (if set on the camera UI).
After some debugging I found out that it did work when I used a 32 bit integer instead of a 16 bit one. I tried to properly rewrite this to the best of my abilities, but I could not get the `_get` function to 'automatically' …
=> White balance adjust on Canon 1300D

camlibs/ptp2/library.c, libgphoto2/gphoto2-camera.c, libgphoto2/gphoto2-filesys.c
Fixes the assert that was in "C_PARAM_MSG" to be correct.
Added more checks.
Return GP_ERROR_NOT_SUPPORTED only if the "partialread" feature is not supported and so fallback should kick in upper level. Otherwise raise errors.
IMPORTANT NOTE: Currently this is not enough to read large files (>64 bits).
Because we are looking at the "compressedSize" that is limited to 32 bits.
=> More fixes for support 64bit getpartialobject for Android in read_file_func

gphoto2/gphoto2.h, libgphoto2_port/gphoto2/gphoto2-port-portability.h
This change enables WIN32 users (MinGW and also Visual Studio, for which I may add some more pull requests soon) to redefine CAMLIBS and IOLIBS in the config.h file. This is useful in order to place the camlibs and iolibs shared libraries in subfolders, so that the file system is more cleaned up. Comments welcome!
=> prevent redefining CAMLIBS and IOLIBS on WIN32

camlibs/directory/directory.c
When reading large files, above 4GiB size, get_file_func() would
eventually calculate a toread value of 0, when reaching size % 4GiB ==
0, and spin forever reading nothing.
=> Use off_t when calculating read size

camlibs/ptp2/library.c
Also made the MP4 type vendor independent
I have the camera. MP4 files are what it generates in video mode.
I didn't add the capture flags, and whether I add them or note I get:
````
$ gphoto2 --capture-image
*** Error ***              
Canon EOS Full-Release failed (0x2019: PTP Device Busy)
ERROR: Could not capture image.
ERROR: Could not capture.
*** Error (-110: 'I/O in progress') ***    
````
I'll debug that to see if I can make it work.
This camera also work in ptpip: if you can figure out the IP address and some other tricks.
=> Added Canon G7 X Mark II USB ID

camlibs/ptp2/library.c
If the GP_FILE_TYPE_EXIF flag is supplied to get_file_func,
the extracted data is missing two bytes. The value for the maxbytes
variable is read from the APP segment size, which does not account
for the two bytes of the marker that is included in the extracted data.
=> Fix incomplete EXIF data extraction

packaging/generic/print-camera-list.c
Since commit 1455cf8dbfd0 ("driver core: emit uevents when
device is bound to a driver") the kernel started emitting
"bind" and "unbind" uevents which confuse the libgphoto2
udev rules.
This caused ID_GPHOTO2 and GPHOTO2_DRIVER udev properties not being set
on devices, causing them not to be visible to user-space that uses those
properties (such as gvfs' gphoto2 backend).
See https://github.com/systemd/systemd/issues/8221
=> print-camera-list: Fix udev rules for linux-4.14+

libgphoto2_port/libgphoto2_port/gphoto2-port-info-list.c
When compiling libgphoto2 using Visual Studio, in one place the compiler chokes on the #warning statement in gphoto2-port-info-list.c. This PR fixes that by checking for _MSC_VER (which should be only set for Visual Studio and maybe MinGW) and uses #pragma warning instead.
=> Fixed compiler error when using #warning on Visual Studio compiler

libgphoto2/gphoto2-setting.c
Here's another PR; gphoto2-port-portability.h undefines the "interface" definition, since "interface" is used throughout libgphoto2, but the Shlobj.h included from gphoto2-setting.c relies on this define. This all only occurs when compiling using Visual Studio and the Windows SDK 8.1 only. I guess MinGW doesn't have this define.
=> Fixed including Win32 shlobj.h header when compiling using Visual Studio

camlibs/ptp2/config.c, po/cs.po, po/da.po, po/de.po, po/es.po, po/fr.po, po/it.po, po/ja.po, po/nl.po, po/pl.po, po/ru.po, po/sv.po, po/uk.po, po/vi.po, po/zh_CN.po
Some lines printed output "Sorry, the property ... is currently ready-only." - this patch changes this to say: "Sorry, the property ... is currently read-only."
=> fixed spelling to read-only

camlibs/ptp2/config.c, camlibs/ptp2/ptp-pack.c
Since at least Canon EOS M50, image size and compression does not
fully describe used image format.
This patch encodes RAW flag (0x8) into image compression value
to correctly decode/encode image format.
=> ptp2: Correctly decode and set cRAW image format for Canon EOS

camlibs/ptp2/library.c
I'm not entirely sure about requiring `PTPBUG_DELETE_SENDS_EVENT`, but I've added it since most other EOS models seem to use that flag. Is there some way I can test this?
=> Added ID for Canon EOS 2000D

camlibs/ptp2/cameras/nikon-coolpix-l810.txt, camlibs/ptp2/library.c
As far as I can tell it has essentially the same capabilities as the L820 so it was a straight copy over with modified vendor IDs
=> add support for Nikon Coolpix L810

camlibs/ptp2/config.c, camlibs/ptp2/ptp.c
* Exposure mode S&Q added.
* Drive modes Continuous Hi+ and Med Speed added.
* All exposure metering modes of A7III added (Multi, Center [weighted average],
Entire Screen Average, Spot Standard/Large, Highlight.
* Shutter speeds 1/5000 ... 1/32000 in ⅓ EV steps added (A9 is claimed to support 1/32000 on E-Shutter)
* Image quality modes for RAW+JPEG Std and X.Fine added
* Reg. PTP2 White Balance linked to Sony properties.
=> Add a few SONY properties for A7III.

libgphoto2_port/Makefile.am
Stop creating the gphoto2 symlink loop in /usr/include/gphoto2/.
The /usr/include/gphoto2/gphoto2 symlink pointing to `.`, i.e.
to /usr/include/gphoto2 was added in 2006 to solve an source
compatibility issue from back then. Fedora have been removing
that symlink from their packaged libgphoto2 packages since 2009,
so it appears those compatibility issues have been solved since
2009.
We should thus be able to remove the symlink now (in 2019).
Resolves: https://github.com/gphoto/libgphoto2/issues/444
=> Remove gphoto2 symlink loop in /usr/include/gphoto2

camlibs/ptp2/config.c
This PR Fixes Nikon D7500 image quality enumeration issue reported by several users in this [INDI thread](https://indilib.org/forum/ccds-dslrs/4604-nikon-dslr-conflict.html).
With this fix, the users can correctly select RAW from the INDI GPhoto driver.
=> Add Nikon D7500 Image Quality

camlibs/ptp2/config.c
I tested with Fujifilm X-T3.
PTP ExposureIndex (0x500F) DataType is defined UINT16 (0x0004).
But Fujifilm X-T3 return INT32 (0x0005).
```
Type of property 'ISO Speed' expected: 0x0004 got: 0x0005
Failed to parse value of property 'ISO Speed' / 0x500f: error code -1
```
Looks like it has been extended to return large (> ISO 51200?) numbers.
=> Support for Fujifilm ISO extension

camlibs/ptp2/library.c
Fixing typo in nikon_wait_busy call
=> Typo fix in nikon_wait_busy call

camlibs/ptp2/library.c
Was surprised to find that I had lost capture preview functionality on my A7s between versions 2.5.23 and 2.5.24. Tracked the regression down to f61a9d965. This PR removes the duplicate and reactivates the original entry at line 1057.
=> Remove duplicate Sony A7s entry with reduced functionality

camlibs/lumix/lumix.c
In lumix camlib, the result of `cam.cgi?mode=accctrl&type=req_acc&value=0&value2=libgphoto/lumix` in `camera_init` can be
ok_under_research_no_msg,GX9-XXXXXX,remote,encrypted
every alternate call for specific models. The same command should be called again to receive
ok,GX9-XXXXXX,remote,encrypted
before proceeding. This logic has been implemented in [GMaster](https://github.com/Rambalac/GMaster/blob/e181ab1684c10d853989beb3bf9361fe6a760639/Core/Camera/Lumix.Internal.cs#L272).
A simplified version is implemented here with a maximum of 3 attempts.
See #409 for more context.
=> lumix: check req_acc return value

camlibs/konica/README.konica, camlibs/panasonic/README.panasonic
Nowadays it's much more widespread than ISO-8859-1, providing
a better chance for proper display.
=> Convert README files to UTF-8

camlibs/ptp2/config.c
This change implements larger steps when changing the shutterspeed. Before the values were changed by the smallest steps possible. Now the the "jump" is calculated according to the distance between current and new value. 
Not all Sony cameras reach the goal. Therefore, we will still need the loop.
Example: Sony a6400 from 30s to 1/4000s took over 40s before and takes now 2.5 seconds.
Even better: For example, Sony a9 can do all changes with only the initial step, so, reaching the goal instantaneously.
=> Speed up Sony shutterspeed changes

camlibs/Makefile.am, camlibs/docupen/Makefile-files, camlibs/docupen/cache.c, camlibs/docupen/calibration.c, camlibs/docupen/docupen.c, camlibs/docupen/docupen.h, camlibs/docupen/huffman.c, camlibs/docupen/huffman.h, camlibs/docupen/image.c, configure.ac
Add camlib for Docupen RC800 wand scanner. Based on Docupen tools by Florian Heinz (https://sourceforge.net/projects/docupen/) and much improved (image correction according to calibration data from scanner, greyscale support).
=> Add Docupen camlib

README.md
This is a followup on #529
The links where not visible on github because the markup was incorrect.
Let me know if there is anything you'd like to see changed
=> Fix markup to make links visible

camlibs/ptp2/config.c
This got broken in 62063e9 almost 6 years ago. There were two issues with
this:
1) At some point the parameter value type got changed from u32 to u16
which would cause bogus parameter data to get printed here.
2) While switching from gp_log(...) to C_PTP_MSG the domain was left there
as a separate parameter which caused a SIGSEV in `vsnprintf` in
gphoto2-port-log.c:116. C_PTP_MSG doesn't take an explicit domain which
resulted in the original domain argument being used as the format string
and the original format string as a parameter for the format string.
This resulted in a "classical" format string argument mismatch which made
`vsnprintf` very unhappy.
=> ptp2: Fix C_PTP_MSG args in _put_Canon_EOS_ViewFinder

camlibs/ptp2/config.c, camlibs/ptp2/ptp.c, camlibs/ptp2/ptp.h
This change makes it possible to query and set the film simulation
for image capture on the camera.
The setting is accessible as "/main/imgsettings/filmsimulation" and
allows setting all the known film simulations supported by the latest
FUJIFILM cameras.
This was tested on an X-T3 with all simulations supported by that camera. I also added the two new simulation in X-T4 but can not test if the codes are indeed correct. I added new simulations in the same order as they were released.
=> Add support for film simulations on FUJIFILM cameras

configure.ac, libgphoto2_port/configure.ac
The versioned test symbols must be external, so move them into the
prologue, otherwise GCC 9.3 (at least) reports "Error: invalid attempt
to declare external version name as default in symbol `f@@VER2'".
Also suppress warnings about missing prototypes and return
statements for these test functions.
=> configure: fix symver support checks

camlibs/lumix/lumix.c
Relates to #409.
I've been using these fixes for a few months and think it's a better default behaviour.
1. Don't change the user-set quality mode
2. Only call `switchToRecMode` when starting a livestream, not continuously throughout
3. Include all AVC_MP4 videos in file listing
=> lumix: enable all video types, do not set quality

camlibs/directory/directory.c, libgphoto2/gphoto2-file.c
this patch updates mime types to recognize CR3 format, this is important e.g. for listing directories
=> mime type update for CR3

camlibs/directory/directory.c, configure.ac
Switch the directory module from the platform-specific `statfs` to the POSIX `statvfs`, so it will work also on any other non-Linux POSIX platform.
=> Directory module: use statvfs for portable storage_info implementation

camlibs/ptp2/config.c, camlibs/ptp2/ptp-pack.c, camlibs/ptp2/ptp.c
This adds support for reading the state of the hardware "Movie Mode" switch setting on Canon EOS cameras as well as switching between still image and movie capture mode in software, without needing to move said switch.
Originally I wanted to implement reading the switch state and setting the mode as a single configuration item but couldn't figure out how to read the device property the regular way and not issue SetDevicePropertyEx commands to set it but only use a custom function.
Also I'm not sure if `_get_Canon_EOS_MovieModeSw` is a good implementation of a "write only"/"action trigger" configuration item (though other implementations nearby do exactly that).
I think this fixes #574
=> Add support for reading Canon EOS MovieMode switch and setting it on/off

camlibs/ptp2/ptpip.c
When PTP/IP IO fails return with `GP_ERROR_IO` instead of continuing on and depending on other branches handling the IO error.
At least in the case of `ptp_ptpip_sendreq` this resulted in the function returning `PTP_RC_OK` which caused the application using libgphoto2 to not detect the error.
=> camlibs/ptp2: Always return after PTP/IP IO errors

camlibs/ptp2/Makefile-files, camlibs/ptp2/fujiptpip.c, camlibs/ptp2/library.c, camlibs/ptp2/ptpip-private.h, camlibs/ptp2/ptpip.c
This PR makes the PTP/IP implementation (regular and Fuji) work on Windows.
Most of the work was wrapping the platform specific quirks/differences between WinSock2 and regular BSD sockets in some macros which abstract away the differences. This also sends the correct hostname to the camera instead of the fixed `gpwindows` string.
- The Fuji implementation is untested as I don't have a Fuji camera.
- The regular implementation was tested with a Canon EOS 77D.
**What I still need help with:**
My autoconf/automake skills are basically nonexistent. The ptp2 camlib need to link to `ws2_32.lib` when building on Windows. For development I worked around that by running `./configure LDFLAGS="-lws_32" ...` but that's not something that should be expected for people to do explicitly.
**Point for …
=> WIP: Make PTP/IP implementation work on Windows

camlibs/ptp2/library.c
This PR adds the vendor and product code for the Nikon Z 7II. It also fixes the VendorExtensionID for the Z 7II (and probably other Nikon cameras) when connecting to the camera over PTP/IP, such as via the built-in Wi-Fi.
**Tested:**
* auto-detect shows "Nikon Z7_2"
* summary command displays the correct Vendor Extension ID "0xa" for Nikon and shows additional configs
* Capture and image download both work over USB and Wi-Fi
=> Recognize Nikon Z 7II and fix VendorExtensionID over PTP/IP

camlibs/ptp2/config.c
This keeps the internal state in sync so that if the control mode
is set to 0 via set-config, subsequent triggers/captures set it to 1.
Some Nikon cameras lock the shutter if in sleep mode. Setting
the control mode to 1 wakes up the camera, allowing the trigger to
proceed.
**Tested:**
Tested on a Nikon Z 7II. I do not know the behavior for other Nikons.
**Additional details:**
On a Nikon camera, when performing a trigger or capture, the control mode is set to 1. This locks the screen and buttons on the camera. To restore the UI, you can run "set-config controlmode=0". However, there is an internal variable that libgphoto2 keeps for the control mode, and that is not updated. On subsequent captures, the control mode is not set to 1 again because libgphoto2 thinks it is already set. I would …
=> Also set params->controlmode in _put_Nikon_ControlMode

camlibs/ptp2/fujiptpip.c, camlibs/ptp2/library.c, camlibs/ptp2/ptpip.c, camlibs/sierra/library.c, camlibs/st2205/st2205.c, examples/config.c, libgphoto2/gphoto2-abilities-list.c, libgphoto2/gphoto2-file.c, libgphoto2/gphoto2-widget.c, libgphoto2_port/serial/unix.c
As noted in https://github.com/gphoto/gphoto2/issues/373 and #552, building on macOS raises errors about implicitly declaring library functions from string.h.
https://github.com/gphoto/libgphoto2/commit/ac4546e0dddf580c7e7558531818423dd3c81c3f partially fixed the issue by defining `_DARWIN_C_SOURCE` in gphoto2-port-info-list.c. In this change, I did the same to all the other files that caused similar errors until `make` stopped returning errors.
=> Make it possible to build libgphoto2 on macOS

camlibs/enigma13/enigma13.c, camlibs/spca50x/spca50x-flash.c, camlibs/spca50x/spca50x-sdram.c, camlibs/st2205/st2205.c
gphoto2-endian.h provides shims for the standard byte swap macros, so
using the standard name is preferred.
=> Fix byte swap calls

camlibs/ptp2/library.c
Starting with firmware version 2.0 the camera supports movie
capture in the X WEBCAM USB connection mode.
=> Add model detection for Fujifilm X100V

camlibs/ptp2/fujiptpip.c, camlibs/ptp2/library.c, camlibs/ptp2/ptpip-private.h, camlibs/ptp2/ptpip.c, libgphoto2/gphoto2-camera.c
The current PTP/IP implementation doesn't have very granular error reporting and returns PTP_RC_GeneralError where a more specific error cause is available. Another issue in situations with flakey and/or suboptimal WiFi coverage is that libgphoto can get stuck on blocking read(), write() or connect() calls when trying to talk to the camera for an undefined amount of time which causes the application using libgphoto to hang (or at least its gphoto thread).
This PR addresses both issues be introducing non blocking socket based communication with timeout as well as adding/adjusting the error codes returned.
This code was tested on Linux, Windows and macOS (mainly with Canon cameras).
=> PTP/IP: Better error reporting and timeout handling

camlibs/ptp2/ptp-pack.c
White implementing a control for the white balance shift I noticed the WhiteBalanceAdjust{A,B} properties where always reported as 0.
After investigating a bit I noticed that changes for `PTP_DTC_INT32` properties weren't being unpacked which resulted in missed updates when the value changes on the camera and libgphoto getting out of sync.
=> camlibs/ptp2: Unpack Canon EOS changes for INT32 properties

camlibs/ptp2/config.c, camlibs/ptp2/library.c
While investigating #653 I fixed some bugs and added a new config option for Fuji cameras.
In this case this is:
- A fix for a wrong property data type in `camera_trigger_capture`
- A new config option to change camera priority mode (USB remote or local camera control)
- Replaced usage of magic numbers with the corresponding DPC #define
- A fix for active live-view (via repeatedly calling `camera_capture_preview`) conflicting with tethered shooting by downloading new images when detected by `camera_wait_for_event`
This is only tested with a Fuji X-T4 as that is what I have access to but I don't think anything should break with other Fuji cameras.
=> Misc Fuji fixes and improvements

camlibs/sierra/library.c, camlibs/sierra/sierra.c, camlibs/sierra/sierra.h
Got an old Epson PtohoPC 500 camera only to find that it does not work with gphoto2.
Seems it has problems with speed over 38400bps, but it works fine in Windows at 115200bps.
Add the same workaround that Windows software uses - write data one byte at a time if the first command times out.
Also found that the camera responds with unknown 0x18 response to the "folder test" command.
=> sierra: Fix Epson PhotoPC 500

camlibs/ptp2/library.c
https://github.com/gphoto/libgphoto2/commit/6c26cdc5b0b8f177bb0d74ea93c8f0d45afb3a09 adjusted `jpgStartPtr` to start after an offset if such is found in the initial blob.
The following `memchr` call was changed to use the adjusted `jpgStartPtr` pointer, but the size parameter was never changed, in theory allowing `memchr` to search in the garbage area past the allocation.
On practice this shouldn't matter because during the previous adjustment it's checked that the following bytes are indeed 0xFF 0xD8 so memchr loop should stop right away, but 1) in theory vectorized memchr might try to read more if it thinks there's enough data to parallelise operations, 2) this can be error-prone in the future and 3) I actually ran into an issue here in combination with a buggy `memchr` implementation …
=> Provide correct search size to memchr

camlibs/ptp2/cameras/sony-a6300.txt, camlibs/ptp2/cameras/sony-a6400.txt, camlibs/ptp2/cameras/sony-a7r.txt, camlibs/ptp2/cameras/sony-dsc-rx0.txt, camlibs/ptp2/cameras/sony-dsc-rx100m5.txt, camlibs/ptp2/cameras/sony-rx10-3.txt, camlibs/ptp2/cameras/sony-rx100m4.txt, camlibs/ptp2/cameras/sony-rx100m5.txt, camlibs/ptp2/cameras/sony-rx100m5a.txt, camlibs/ptp2/cameras/sony-rx100m6.txt, camlibs/ptp2/cameras/sony-rx1rm2.txt, camlibs/ptp2/config.c
This PR contains various fixes for Multi-Frame Noise Reduction ISO mode in Sony cameras.
- Add support for distinguishing Standard vs High modes for Multi Frame Noise Reduction.
Previously those would be rendered as separate options with the same name, making it impossible to choose the correct one or switch from one to another.
Now the high mode is indicated by the `+` suffix.
- Fix higher ISO values for MFNR too.
Previously a mask 0xffff was used, which was incorrect and didn't cover higher ISO values. As a result, they were rendered incorrectly.
Instead, base ISO should be read with 0x00ff_ffff mask, and the highest byte then indicates the MFNR mode (0 for disabled, 1 for Standard, 2 for High). This also simplifies the logic for Auto ISO, since it's correctly covered by the updated …
=> Revamp Sony ISO MFNR logic

camlibs/ptp2/config.c
An example where I ran into this: Sony a6600 reports values [25, 50, 64, 80, 100, 125, 160, 200, 250, 320, 400, ...] as supported with Multi Frame Noise Reduction. However, among those values the camera only allows selecting between [100, 200, 400].
As a result, switching even between valid values - say, ISO 100 with MFNR and ISO 3200 without MFNR - was calculating incorrect offset, overshooting in one direction, calculating new incorrect offset, overshooting in another direction, and so on leading to an infinite loop.
=> Fix infinite loop when setting Sony values

camlibs/canon/library.c, camlibs/ptp2/config.c
Without this, widgets for things like "Serial Number", "Manufacturer", "Battery level" etc. would be created as writable, even though they are not.
It it possible to special case them in GUI frontends when rendering (e.g. by making everything under "status" section readonly anyway), but it seems better to return correct readonly status for such properties from libgphoto2 itself.
=> Mark properties without setters as readonly

camlibs/ptp2/config.c
Apparently Sony reports shutter speeds that are integer seconds as "300/10", "250/10", "200/10" etc. This happens both on Sony a6600 I currently have as well as I can see this when searching for 0xd229 among camlibs/sony-*.txt - that is, even models with enums use this format.
Interestigly, setting shutter speeds accept either form, so what happened is you could set shutter speed to e.g. "5" and camera would change it, but then camera would report back "50/10" which is no longer valid value for the shutter speed widget.
This PR normalizes all such shutter speeds to their integer form, so that "5" would be reported back as well in such scenario.
=> Normalize Sony shutter speeds

camlibs/ptp2/library.c
I've noticed consistent memory increase while streaming preview from a Sony camera. Building with `-fsanitize=leak` revealed that the leak is coming from `strdup <- ptp_unpack_string <- ptp_unpack_OI <- ptp_getobjectinfo`.
Apparently, `PTPObjectInfo` contains heap-allocated strings for `Filename` & `Keywords`, and so `ptp_free_objectinfo` always must be called on the `ptp_getobjectinfo` results.
That all sounds good, but what seriously worries me is that, after fixing this particular codepath for PTP_VENDOR_SONY, I've searched for other usages of `ptp_getobjectinfo`, and majority of them don't ever call `ptp_free_objectinfo` on the result.
That is, there's probably tons of other leaks out there for various cameras just out of this single call, and someone needs to go through all those …
=> Fix memory leak in capture preview for Sony

camlibs/ptp2/library.c
Without this, camera abilities would report a6600 as not having "trigger capture" even though it works on practice.
=> Add Sony a6600 descriptors

camlibs/ptp2/ptp-pack.c
My wife's EOS RP (FW 1.4.0) always reports the lens' lowest aperture unless we apply the same special handling which is enabled for `olcver == 0x13` (apparently, EOS R5). Tested with RF 35/1.8, and also on 5Div + Sigma 35 Art (to check a possible regression).
This reverts commit 5bf98e7f09e82d0e27f41a8df4ccb10e5feb6944 (and fixes a comment so that it more accurately reflects what's going on). I'm a bit nervous about this because that commit looks like it was explicitly designed to do the exact opposite of this one, but perhaps it was just to be extra cautious?
Cc: @arkellr @msmeissn
=> camlibs/ptp2/ptp-pack.c: Fix aperture on EOS RP

camlibs/ptp2/config.c, camlibs/ptp2/ptp-pack.c
This supports just the Enabled/Disabled choices as defined in the camera menu (on RP, Menu -> Shooting -> 5 -> Movie Servo AF). Even when active, the servo AF can be suspended by tapping the LCD screen at the bottom left corner with a green "SERVO AF" button; I do not see any PTP property getting changed upon suspend/resume.
Tested on EOS RP and on 5Div.
Related-bug: #700
=> Canon: basic control over Movie Servo AF

camlibs/ptp2/config.c
I picked C2 and C3 while the existing one is called "Custom"; I think the naming is a bit ad hoc (full words like "Manual" and "Bulb" vs. all-caps abbreviations "AV" and "TV" vs. "Fv" which is spelt as-is on the mode dial).
Also add the "HDR" thingy for HDR movies as available on RP.
=> Add mode dial positions available on EOS RP or 5Div

.github/workflows/ccpp.yml, .github/workflows/codeql-analysis.yml
As 4316f75ed4ce7a4ae5296264699665631c4e62d6 has removed gp2ddb with its use of `flex` and `bison`, we do not need `flex` and `bison` any more, and so the github workflows do not need to install `flex` and `bison` either.
I have made this a PR mainly to get github to actually run the workflows to check.
=> gh workflows: remove requirements for flex, bison

packaging/generic/print-camera-list.c
Use “version” instead of “mode” to avoid confusion with the “(file) mode” argument.
=> print-camera-list: clarify help

camlibs/ptp2/cameras/canon-ixus132.txt, camlibs/ptp2/library.c
I tried to test if 'PTPBUG_DELETE_SENDS_EVENT' is really needed but couldn't trigger a test case. I then kept it because all similar cameras have this flag
=> ptp2: add Canon IXUS 132

camlibs/ptp2/config.c, camlibs/ptp2/library.c
Please add Nikon Zfc support. With this applied the Zfc no longer reports 
```
*** Error ***              
liveviewsize not found in configuration tree.
```
when doing a 
`gphoto2 --set-config liveviewsize=2 --stdout --capture-movie `
=> Add Nikon Zfc support

camlibs/pentax/js0n.c
This catches clang in a clang specific C preprocessor conditional
before clang gets a chance to mess up at pretending to be gcc.
The camlibs/pentax/js0n.c state machine tables use a lot of both
GNU style range designators [ a ... b ], and later overrides some
of the values in the range. This is not very pure C, but relatively
effient to code, so we can accept silencing some warnings here.
Fixes: https://github.com/gphoto/libgphoto2/issues/761
=> Allow clang compile with initializer overrides

NEWS, libgphoto2.pc.in, libgphoto2_port/libgphoto2_port.pc.in
In the *.pc files, use a C preprocessor include path both with
and without the gphoto2/ path component:
Cflags: -I${includedir} -I${includedir}/gphoto2
This allows both the preferred way to include gphoto2 headers
#include <gphoto2/gphoto2.h>
#include <gphoto2/gphoto2-camera.h>
and also the early 2000s legacy way (still in use by kamera and
others because we did not properly communicate and enforce that
back when we were still stabilizing the API)
#include <gphoto2.h>
#include <gphoto2-camera.h>
to produce builds with the libgphoto2 headers actually corresponding
to the *.pc files in use.
Any other option for the *.pc file Cflags either produces
unintended build failures or builds which use the wrong header
files (the `-I${includedir}/gphoto2` option), or breaks the
`#include <...>` part …
=> pc files: Fix gphoto2 builds, avoid builds with wrong headers

.github/workflows/ccpp.yml, NEWS, examples/ambs-lgp2-frontend/.gitignore, examples/ambs-lgp2-frontend/Makefile.am, examples/ambs-lgp2-frontend/README.md, examples/ambs-lgp2-frontend/configure.ac, examples/ambs-lgp2-frontend/main.c
Add automake based example project using libgphoto2 to have
the CI builds ensure that building a libgphoto2 client with
this libgphoto2 is possible.
=> CI: add automake based example project using libgphoto2

po/de.po
In this context release is the opposite of press in the sense of
"loslassen" (see translation of other choices).
=> Fix german translation of eosremoterelease choices

camlibs/ptp2/cameras/sony-a7m4.txt, camlibs/ptp2/config.c, camlibs/ptp2/library.c
This is another case of ptp_sony_9280 causing USB to hang.  Ref #85
Add ILCE-7M4 to the exclude of the ptp_sony_9280 call.
This is followed by two further patches.
One, adding the USB ID for the device, which isn't strictly necessary, but nice to have.
And the other filling in the obvious missing values in CompressionSetting and AspectRatio.
=> Add Sony Alpha 7 IV (ILCE-7M4) Support

camlibs/ptp2/library.c
Previously there was no support for Panasonic cameras in `camera_trigger_capture` but only in `camera_pansonic_capture` (which gets called by `camera_capture`).
While `camera_capture` works it's not useful for the application I'm working on, as `camera_capture` also downloads the captured image as part of calling it.
=> ptp2: Add support for Panasonic cameras in camera_trigger_capture

.github/workflows/ccpp.yml
On the `ubuntu-latest` workers (which appear to be the same as `ubuntu-20.04`, installing `libgd-dev` fails as follows:
```
The following packages have unmet dependencies:
libgd-dev : Depends: libgd3 (= 2.2.5-5.2ubuntu2.1) but 2.3.3-5+ubuntu20.04.1+deb.sury.org+1 is to be installed
E: Unable to correct problems, you have held broken packages.
```
This tries to fix or work around that.
PR to make the workflow run.
=> gh workflow: trying to fix libgd-dev dependency issue

.github/workflows/ccpp.yml
We probably do not need to dist-upgrade (or upgrade), and dist-upgrade
can take a long time on the github runners.
We only had this while trying to work out how to work around the
libgd-dev dependency issue, so we can remove the dist-upgrade step.
=> gh workflow: remove apt-get dist-upgrade

camlibs/ptp2/ptp.c
https://github.com/gphoto/libgphoto2/blob/129a2ab9fa35db05af78b9d6ecf2576d387e4828/camlibs/ptp2/ptp.c#L721-L744
This line clearly should follow the `for` loop instead of being part of it:
https://github.com/gphoto/libgphoto2/blob/129a2ab9fa35db05af78b9d6ecf2576d387e4828/camlibs/ptp2/ptp.c#L736
Since the `len` variable does not change, it makes no sense to repeat the assignment on every iteration.
At the same time, if the length is 0, then nothing will be assigned at all, resulting in a string without a null-terminator.
=> Fix empty PTP strings not being null-terminated in parse_9301_value()

libgphoto2_port/libgphoto2_port/gphoto2-port-portability.c
I noticed this in my logs and... according to Git blame it's been there for over 21 years? 😂
=> Remove printf leftover

camlibs/jd11/serial.c, camlibs/konica/library.c, camlibs/pccam600/library.c, camlibs/pentax/library.c, camlibs/ptp2/library.c, camlibs/ricoh/g3.c, camlibs/sipix/blink.c
I've noticed in my tests that for many files the CameraFileInfo incorrectly had `info.audio` marked as available (with various flags).
Thanks to valgrind I found that it's because `CameraFileInfo` is zero-filled in some places, but not others, so the `audio.fields` (as well as entire `audio`) was filled with uninitialized data.
I tried to find all usages of `info.file.fields = ...` and `info.preview.fields = ...` and zero-initialize them in the same way as it already is in other places.
=> Zero-fill CameraFileInfo

libgphoto2_port/vusb/vcamera.c
- Consumers won't have to guess the path (which depends on the version of the library).
- Consumers don't have to have access to the path (/usr/share/...) might be readonly to them.
- Consumer can point VCAMERADIR to a temporary directory, ensuring a clean slate before each test.
=> Allow customizing vcamera directory at runtime

camlibs/ptp2/library.c
Preview and image capture work in both USB TETHER SHOOTING AUTO & FIXED modes.
=> Add support for Fujifilm X-H2

camlibs/ptp2/config.c, camlibs/ptp2/ptp.c, camlibs/ptp2/ptp.h
Adds the following A7R3/A7R3A settings:
- 'Focus Area'  => Auto focus area control
/main/capturesettings/focusarea
Label: Focus Area
Readonly: 0
Type: RADIO
Current: Wide
Choice: 0 Wide
Choice: 1 Zone
Choice: 2 Center
Choice: 3 Flexible Spot: S
Choice: 4 Flexible Spot: M
Choice: 5 Flexible Spot: L
Choice: 6 Expand Flexible Spot
END
- 'Live Display: Setting Effect ON/OFF' => Toggle exposure in live view / preview image
/main/capturesettings/liveviewsettingeffect
Label: Live View Setting Effect
Readonly: 0
Type: RADIO
Current: Off
Choice: 0 On
Choice: 1 Off
END
Likely these exist on other Sony cameras as the property ids were commented out in ptp.h previously.
Tried to name them like the Sony settings in the camera manual but slightly more concise, let me know if you want different naming. …
=> Add 2 new settings metadata for Sony A7R3

camlibs/jd11/serial.c
Adding pointer allocation check may help the program be more robust.
=> serial: Add check after malloc allocation

camlibs/ptp2/config.c, camlibs/ptp2/ptp.h
This is useful for remotely dialing in focus when viewing the live view / preview images.
The following toggle actions control the focus assist magnification:
- focusmagnify      : enter focus magnification mode, toggles through magnification levels
- focusmagnifyexit  : exit focus magnification mode, back to normal live view / preview image
- focusmagnifyup    : move magnification zone up
- focusmagnifydown  : move magnification zone down
- focusmagnifyleft  : move magnification zone left
- focusmagnifyright : move magnification zone right
These are toggle actions and may need to be set twice to be noticed by the camera:
gphoto2 --set-config=focusmagnify=1 --set-config=focusmagnify=0
gphoto2 --set-config=focusmagnifyexit=1 --set-config=focusmagnifyexit=0
=> Add properties to control Sony focus assist magnification

camlibs/ptp2/library.c
This fixes a crash running "gphoto2 --summary" when there is a PTP property which is a very long array overflowing the buffer. It also truncates the long array - not sure if 64 is the appropriate value to truncate at.
The problem was triggered by this property from an Olympus E-M1 II:
Property 0xd405:(read only) (type=0x4002) a[74752] 0,0,1,0,5,0,0,0,0,0,1,0,32,0,223,222,0,0,86,0,0,0,48,48,0,0,1,0,32,0,168,37,0,0,53,223,0,0,32,32,0,0,1,0,32,0,168,16,0,0,221,4,1,0,24,24,0,0,1,0,32,0,136,9, ...
=> Fix string overflow in camera_summary

README.md
I've forked the old (now 9 years without a commit, so presumably abandoned) Go bindings ([aqiank/go-gphoto2](https://github.com/aqiank/go-gphoto2)), and have done some work modernizing them for use with the modern Go toolchain which was not possible with the old bindings. The new bindings can be found at [weebney/gphoto2-go](https://github.com/weebney/gphoto2-go)—I intend to maintain them and do some major overhauling to these in the coming months as I would like to use them in a project.
This pull request updates the readme to recommend my fork instead of the out-of-date bindings.
=> Update Go bindings to new package in readme 

AUTHORS, camlibs/Makefile.am, camlibs/quicktake1x0/Makefile-files, camlibs/quicktake1x0/qtk-helpers.c, camlibs/quicktake1x0/qtk-thumbnail-decoder.c, camlibs/quicktake1x0/qtkn-decoder.c, camlibs/quicktake1x0/qtkt-decoder.c, camlibs/quicktake1x0/quicktake1x0.c, camlibs/quicktake1x0/quicktake1x0.h, configure.ac, gphoto2/gphoto2-file.h, libgphoto2/gphoto2-file.c
- Summary
- Get/Set configuration
- Get preview
- Get PPM files
- Get raw files (QTK format)
Serial protocol reference: https://www.colino.net/wordpress/en/archives/2023/10/29/the-apple-quicktake-100-serial-communication-protocol/ QTKT / QTKN decoding algorithms from dcraw (GPL licensed).
Running on gtkam:
Example photo (after conversion from ppm):
=> Add support for QuickTake 100/150

camlibs/digita/serial.c, camlibs/directory/directory.c, camlibs/enigma13/enigma13.c, camlibs/jd11/serial.c, camlibs/jl2005c/jl2005c.c, camlibs/kodak/dc120/dc120.c, camlibs/kodak/dc120/library.c, camlibs/kodak/dc210/library.c, camlibs/mars/mars.c, camlibs/mustek/io.c, camlibs/mustek/rs232.c, camlibs/mustek/usb.c, camlibs/panasonic/coolshot/library.c, camlibs/polaroid/pdc320.c, camlibs/ptp2/fujiptpip.c, camlibs/ptp2/ptpip.c, camlibs/quicktake1x0/qtk-helpers.c, camlibs/quicktake1x0/quicktake1x0.c, camlibs/sonydscf55/sony.c, camlibs/spca50x/spca50x.c, camlibs/toshiba/pdrm11/pdrm11.c
=> Fix build on Mac OS X

camlibs/mars/mars.c
=> camlibs/mars: Fix copy-paste mistake in mars_white_balance()

camlibs/kodak/dc120/dc120.c, camlibs/kodak/dc120/library.c, camlibs/panasonic/coolshot/library.c, camlibs/ptp2/fujiptpip.c, camlibs/ptp2/ptpip.c, camlibs/st2205/st2205.c
Fix the FreeBSD build by defining the appropriate
C preprocessor macros such that the libc headers
define prototypes for the functions used.
=> Fix FreeBSD build

libgphoto2_port/gphoto2/gphoto2-port-info-list.h, libgphoto2_port/libgphoto2_port/libgphoto2_port.ver
in one of two versions of code, but not used anywhere. Noted in NEWS as removed. It breaks compilation in some systems.
=> LIBGPHOTO2_INTERNAL: Symbol gpi_gphoto_port_type_map is present

camlibs/ptp2/config.c, camlibs/ptp2/library.c
Fix had already been applied for one instance (https://github.com/gphoto/libgphoto2/commit/5f9f6c87189d3223fb26d2db9a6a1a825bda9cf2), I've found all instances and applied the same fix.
I believe this fixes (at least) #950
=> add fixes in case `PTP_DPC_FUJI_PriorityMode` not available (e.g. Fujifilm X100V)

camlibs/ptp2/library.c
Analysis shows that when the camera failed was when a DevicePropCode > 16bit was being used. In this particular case it is the MovieTVLockSetting in the Z9, with the propcode `0x1D00F`. The event.Param1 variable is a uint32, and the function `ptp_generic_getdevicepropdesc` expects a uint32, so the bitmask is a bit strange here, also causing the program to crash since it will result in a non-existing propcode.
I also updated the prints to show the full 32bit values, instead of only 16 bits.
My test program now runs without issue on the Z9.
For issue #987
=> Removed bitmask from devicepropchanged call that crashed using Nikon Z9

camlibs/ptp2/config.c, camlibs/ptp2/library.c, camlibs/ptp2/ptp.c, camlibs/ptp2/ptp.h
Several Canon EOS cameras allow software setting of the exposure mode dial. This is supported by `libgphoto2` via the `autoexposuremodedial` config.
This works as expected wit for instance the EOS 1200D and the EOS 2000D. 
In some Canon cameras, for instance the Canon EOS R50,  you need to unlock this feature before it can be used. 
The `SetModeDialDisable` opcode (`0x9088`) has to be sent to the camera with parameter 0 to disable the mode dial and allow software setting of the exposure mode.
The disabling is cancelled by sending the `SetModeDialDisable` command with parameter 1.
This pull request will allow software setting of the exposure mode during a camera session by issuing the `SetModeDialDisable` as described above, by enabling software setting in `camera_init` and disabling it in …
=> Support the SetModeDialDisable opcode for Canon cameras

camlibs/ptp2/config.c
Adding M50m2 to exception list results in preview size increase from 480x320 to 960x640
=> Fix Canon EOS M50 Mark2 preview size

libgphoto2_port/libgphoto2_port/gphoto2-port-log.c
Issue: #996 
Instead of allocating _before_ knowing if it is necessary and thus wasting precious clock cycles, we instead allocate only when a log function shall log the data.
Example: When downloading a large video file from the Nikon Z9, we go from 60s to 6-8s, when using the log level "ERROR".  Before, we allocated for every log message that shouldn't even be logged.
=> Only allocate when a logging functions needs it

.editorconfig
The main goal here is convince editors to use tabs for indentation. Details can be found on https://editorconfig.org/.
=> minimal .editorconfig file to prevent reintroduction of spaces

camlibs/ptp2/library.c, camlibs/ptp2/ptp-pack.c, camlibs/ptp2/ptp.h
Unpacking canon EOS event data uses heap memory stored in `char *info` for different types of information (mostly PTP_CANON_EOS_CHANGES_TYPE_UNKNOWN but also PTP_CANON_EOS_CHANGES_TYPE_FOCUS*). This memory needs to be freed on every call-sight of ptp_get_one_eos_event, which it wasn't and it needs to do so for every type using it, but if at all, it only freed it for PTP_CANON_EOS_CHANGES_TYPE_UNKNOWN data.
This patch replaces `char *info` with `char info[84]` and introduces a macro called PTP_CANON_SET_INFO() for setting that data. 84 is used, because the union is at least that large anyway because of the `object` member and 84 is sufficient for all current use cases. The macro makes sure there is no buffer overflow in the future.
This change does away with the error prone task of freeing …
=> fix memory leaks related to PTPCanon_changes_entry.u.info

.cirrus.yml
FreeBSD 13.2 reached end-of-life (EOL) as of July 1st, 2024.
=> Update CI to FreeBSD 13.3

camlibs/ptp2/config.c, camlibs/ptp2/library.c, camlibs/ptp2/ptp-private.h
Instead of calling ptp_canon_eos_keepdeviceon() in e.g. camera_wait_for_event() directly for every invocation (often twice), which can lead to dozens of those calls per second, this patch limits the number to 1 every 10 seconds.
The camera_prepare_capture + ptp_check_eos_events + keepdeviceon block in camera_lookup_by_property has been removed completely as this function is only called from within camera_wait_for_event() where those checks have been made just prior to the call to camera_lookup_by_property.
Furthermore: ptp_check_eos_events() will now only be called inside camera_wait_for_event if the queue of already transmitted events is drained first.
=> new camera_keep_device_on() function (less noise in debug log)

camlibs/ptp2/ptp-pack.c, camlibs/ptp2/ptp.c, camlibs/ptp2/ptp.h
A full logging excerpt now looks like this
```
event 237: EOS event OLCInfoChanged (size 81, version 0x0b, mask 0x1fff)
0x00: 49 00 00 00 ff 1f 00 00 01 00 01 01 a0 10 00 a0
0x10: 01 01 50 20 2c 01 01 00 00 04 01 01 71 00 00 00
0x20: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00
0x30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0x40: 00 00 00 00 00 00 00 00 00
event 237: olcmask 0x0001, 2 bytes: 01 00
event 238: olcmask 0x0002, 6 bytes: 01 01 a0 10 00 a0
event 239: olcmask 0x0004, 5 bytes: 01 01 50 20 2c
event 240: olcmask 0x0008, 4 bytes: 01 01 00 00
event 241: olcmask 0x0010, 4 bytes: 04 01 01 71
event 242: olcmask 0x0020, 6 bytes: 00 00 00 00 00 00
event 243: olcmask 0x0040, 8 bytes: 01 00 00 00 00 00 00 00
event 244: olcmask 0x0080, 4 bytes: 00 00 00 00
event 245: olcmask …
```
=> ptp2: condense EOS OLCInfo related debug output

camlibs/ptp2/ptp-pack.c, camlibs/ptp2/ptp.c, camlibs/ptp2/ptp.h
This makes the event entries in the log from an EOS more readable by removing uninteresting information and layout out interesting information in a more aligned/table based manner for quick visual parsing of the data.
Example excerpt:
```
event 104: EOS prop d1c9 value changed, size  4 (EOS_ContinousAFMode)
value of d1c9 is 0x00000000 (u32)
event 105: EOS prop d19f value changed, size  4 (EOS_GPSDeviceActive)
EOS prop d19f is unknown
value of d19f is 0x00000001 (u32)
[...]
event 111: EOS prop d177 value changed, size 24 (EOS_SmartphoneShowImageConfig)
0x000: 18 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0x010: 00 00 00 00 00 00 00 00
event 112: EOS prop d105 options changed, type 1, count  0 (EOS_AutoExposureMode)
event 113: EOS prop d108 options changed, type 3, count  3 …
```
=> reduce textual 'noise' in the EOS event debug log entries

.cirrus.yml, .github/workflows/ccpp.yml, Makefile.am, NEWS, camlibs/Makefile.am, configure.ac, doc/Makefile.am, libgphoto2/Makefile.am, libgphoto2_port/Makefile.am, libgphoto2_port/configure.ac, libgphoto2_port/gphoto-m4/gp-gettext-setup.m4, libgphoto2_port/libgphoto2_port/Makefile.am
Enable silent build rules by default.
You can still use verbose build rules by using any of the following
methods:
* run `configure` with the `--disable-silent-rules` argument
* run `make` with the `V=1` argument
This hides the compiler command line which makes debugging users'
problems more difficult. To compensate for that, this prints the
build flags separately, but a lot less frequently:
For each part of the build (`libgphoto2_port.la`, iolibs,
`libgphoto2.la`, camlibs), if something of that part has been
rebuilt, prints the build flags (_CPPFLAGS, _CFLAGS, _LIBADD,
_LDFLAGS) once.
Always prints the environment variables CPPFLAGS CFLAGS LDADD
LIBADD LDFLAGS once, whether they are the defaults the configure
script sets or given on the `make` command line.
Not all make recipes have been …
=> Enable silent build rules by default

camlibs/ptp2/config.c, camlibs/ptp2/library.c, camlibs/ptp2/ptp-pack.c, camlibs/ptp2/ptp.c
3 random commits, pushing it now because of the first one (fix for a minor display bug I introduced in the last PR).
=> Mostly cosmetic

camlibs/ptp2/chdk.c, camlibs/ptp2/config.c, camlibs/ptp2/fujiptpip.c, camlibs/ptp2/library.c, camlibs/ptp2/olympus-wrap.c, camlibs/ptp2/ptp-pack.c, camlibs/ptp2/ptp-private.h, camlibs/ptp2/ptp.c, camlibs/ptp2/ptp.h, camlibs/ptp2/ptpip.c, camlibs/ptp2/usb.c
This is basically code cosmetic that prepares the removal of `params->canon_props` member and accompanying EOS specific handler functions.
=> More code cosmetic

camlibs/ptp2/ptp.c
Generally looking for MTP prop names when searching for a Canon prop was the wrong approach. This leads to "Aperture" beeing called "Secure Time".
Instead just copy the 3 MTP prop names actually required into the Canon prop name list.
=> ptp2: fix a regression in ptp_get_property_description

camlibs/ptp2/library.c, camlibs/ptp2/ptp-pack.c, camlibs/ptp2/ptp.c, camlibs/ptp2/ptp.h
Mostly code and log readability improvements + plus a fix for an autofocus regression, I introduced earlier :-/.
=> EOS event naming

camlibs/lumix/lumix.c, camlibs/ptp2/chdk.c, camlibs/ptp2/config.c, camlibs/ptp2/library.c, camlibs/ptp2/olympus-wrap.c, camlibs/ptp2/ptp-pack.c, camlibs/ptp2/ptp-private.h, camlibs/ptp2/ptp.c, camlibs/ptp2/ptp.h, libgphoto2_port/vusb/vcamera.c
This is a whole bunch of rather trivial renaming patches with the goals to:
* increase internal consistency
* increase consistency with specification
* increase readability
If I didn't screw up, this is only changing names of symbols and fixes whitespace where affected. It does not change the
behavior of the code in any way.
=> PTP symbol naming

.github/workflows/ccpp.yml, .github/workflows/codeql-analysis.yml, camlibs/ptp2/config.c, camlibs/ptp2/library.c, camlibs/ptp2/ptp-pack.c, camlibs/ptp2/ptp.c, camlibs/ptp2/ptp.h, libgphoto2_port/vusb/vcamera.c
Details see commit messages. Please note the two TODOs mentioned in the first commit.
=> PTPObjectInfo related improvements

camlibs/ptp2/Makefile-files, camlibs/ptp2/array.h, camlibs/ptp2/config.c, camlibs/ptp2/library.c, camlibs/ptp2/ptp-pack.c, camlibs/ptp2/ptp-private.h, camlibs/ptp2/ptp.c, camlibs/ptp2/ptp.h, libgphoto2_port/gphoto2/gphoto2-port-result.h, libgphoto2_port/vusb/vcamera.c
More use of the new array abstraction in the ptp2 camlib and some minor cleanups along the way. The PTPParams struct is now completely converted to use the array macros. Also more preparation steps towards merging `dpd_cache` and `canon_props`.
There is a new `TODO` and a `FIXME` comment related to old/potential bugs.
=> More array abstraction use in ptp2

camlibs/Makefile.am, doc/Makefile.am, libgphoto2_port/gphoto-m4/gp-set.m4
Replace the use of doxygen `-q` argument by redirecting stdout and stderr to make silent rule builds work with doxygen older than release 1.9.2 which added `-q`.
=> Fix silent doxygen rule

camlibs/ptp2/config.c
It will change the content of the "imageformat" widget, e.g. "cRAW + Large Fine JPEG" becomes "cRAW + L". This has been discussed in #1031.
=> ptp2: switch imageformat widget to new implementation for Canon

camlibs/ptp2/cameras/sony-a7r5.txt, camlibs/ptp2/ptp-pack.c, camlibs/ptp2/ptp.c, camlibs/ptp2/ptp.h
Mark settings such as ISO, Shutter Speed as read/write when using version 2 of the Sony PTP protocol.
=> ISO / Shutter set fix for Sony cameras

camlibs/ptp2/config.c, camlibs/ptp2/library.c, camlibs/ptp2/ptp-pack.c, camlibs/ptp2/ptp.c, camlibs/ptp2/ptp.h
- Fixes for Sony mode 3 (for A7R4/A7R5):
- capturemode
- flashmode
- iso
- shutterspeed
- f-number
- focusmagnify
- capture-image-and-download
- Allow the following settings to be settable in mode 2 (for A7R3):
- focusmode
- flashmode
- exposure metering
- Re-enabled mode 3 for A7R5, so that:
- iso enum is reported
- focus magnify can be set
- manual focus can be adjusted
=> Fixes for Sony A7R3/4/5

README.md, doc/Doxyfile.in
Added build instructions in the readme instead of pointing to the project's documentation.
=> Update build instructions to resolve #1083, enable search engine in generated doc

camlibs/ptp2/config.c, camlibs/ptp2/ptp.c, camlibs/ptp2/ptp.h
Works with protocol 3 enabled cameras.  E.g. A7R5.
=> Add image stabilization / SteadyShot setting for Sony cameras.

camlibs/ptp2/library.c, camlibs/ptp2/ptp.c
While working on things (in this case trigger capture support for Olympus OM-D) I usually run my tests with asan/ubsan enabled.
After I figured out how to get them to play nicely with `libtool`s dynamic loading/unloading (by building with `-DVALGRIND` so no unloading happens at the end) I finally managed to track down some memory leaks that I've seen quite a few times previously but didn't know where they happened apart from "inside libgphoto2".
=> Fix some memory leaks

packaging/generic/print-camera-list.c
With this applied print-camera-list will get a JSON output format that looks like this:
```json
[
{"camlib": "ptp2", "id": "PTP", "model": "Apple iPad (PTP mode)", "usb-vendor": "05ac", "usb-product": "129a"},
{"camlib": "ptp2", "id": "PTP", "model": "Apple iPad Air", "usb-vendor": "05ac", "usb-product": "12ab"},
{"camlib": "ptp2", "id": "PTP", "model": "Apple iPhone (PTP mode)", "usb-vendor": "05ac", "usb-product": "1290"},
{"camlib": "ptp2", "id": "PTP", "model": "Apple iPhone 3G (PTP mode)", "usb-vendor": "05ac", "usb-product": "1292"},
{"camlib": "ptp2", "id": "PTP", "model": "Apple iPhone 3GS (PTP mode)", "usb-vendor": "05ac", "usb-product": "1294"}
]
```
This is useful if you want to do something with the list of available cameras, e.g. create INF driver files for Windows with a …
=> Add JSON output support to print-camera-list

gphoto2/gphoto2-setting.h, libgphoto2/gphoto2-setting.c, libgphoto2/libgphoto2.sym
This is useful for applications integrating libgphoto2 which provide their own way of storing user settings.
E.g. in my dayjob I use libgphoto in Qt based applications that use QSettings to store their preferences as storing the settings in the users HOME dir isn't always what we want.
There are cases where one application (and it's settings) are used by multiple user accounts on the same PC and per-user settings would be a problem for PTP/IP pairing as the device GUID is stored in the libgphoto2 settings.
I think merging this would require changing AGE/REVISION/CURRENT, right? I think only AGE needs to be adjusted but I don't quite get how that works
=> Allow redirecting `gp_settings_{get,set}` to user defined functions

camlibs/ptp2/config.c, camlibs/ptp2/ptp.h
I added names/defines for a few of the unnamed settings of an OM-D E-M1 Mark 2.
There is still an issue with the WB adjust though: On the camera the range is ±7 however it gets reported as follows:
In my application: 
```
[…]
[RW] [whitebalanceadjusta] WhiteBalance Adjust A (Radio): Choices: ["65529", "65530", "65531", "65532", "65533", "65534", "65535", "0", "1", "2", "3", "4", "5", "6", "7", ] Value: "2"
[RW] [whitebalanceadjustb] WhiteBalance Adjust B (Radio): Choices: ["65529", "65530", "65531", "65532", "65533", "65534", "65535", "0", "1", "2", "3", "4", "5", "6", "7", ] Value: "65534"
[…]
```
In `gphoto2 --summary` (the one from the OS which doesn't have my changes in it):
```
[…]
Property 0xd161:(readwrite) (type=0x4) Enumeration …
```
=> Add color temperature, WB adjust for Olympus OMD

libgphoto2/libgphoto2.sym, libgphoto2/meson.build, libgphoto2/sym_to_ver.py, libgphoto2_port/libgphoto2_port/meson.build, meson.build
Necessary for compatibility with the autotools+libtool-built libraries.
Also add the missing export of `gp_filesystem_get_storageinfo`.
---
I've tried to replicate what autotools does. I'm not sure the version script for `libgphoto2` is necessary (AFAICT libtool doesn't add any versions), but the one for `libgphoto2_port` is.
In any case, when comparing the products notice I noticed `gp_filesystem_get_storageinfo` was no longer exported, so I added it to `libgphoto2.sym`.
=> meson: Add missing version info
